### ISSUE TITLE
[CTD] After updating to ExtraGolem 6.02

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopment/Extra-Golems#1]
http://pastebin.com/Yb6sq8Xd
Seems to come from BaseMetal Golem though

**Comment by sky0-1** [comment]
Thank you for the prompt report. Base Metal Golems will be updated to support Extra Golems 6.02, as will Modern Metal Golems.
Check back here in a few hours.

**Comment by drakray** [comment]
nice to hear, I'll use 6.01 until then :)

**Comment by sky0-1** [comment]
Base Metal Golems has been updated and tested with Extra Golems 6.02 with no errors.

Modern Metal Golems will be updated next.
