### ISSUE TITLE
Tinker's Construct Raw Ore Bug

### ISSUE THREAD

**Issue by AveryCorvus** [MinecraftModDevelopment/Extra-Golems#101]
As of the most recent version of Extra Golems, which added Tinker's Construct compatibility, when you melt Raw Iron Ore or Raw Copper Ore in Tinker's Construct it gives you 9 ingots instead of the normal amount.

With only the two mods + JEI installed, this is the recipe page for melting iron ore. This also applies to Copper and Gold, but not to Tinkers' own Cobalt.

![2022-06-30_21 57 39](https://user-images.githubusercontent.com/10104456/176808316-c37ad87b-8416-446f-ae5e-eb8e056f02d8.png)

No other mod causes this effect; I have a modpack with ~100 mods and was able to narrow the issue down to Extra Golems, as well as the test pack with 3 mods described above.

**Comment by skyjay1** [comment]
This is simply not possible. I don't do anything to Tinkers, I only check if it is loaded. There is no recipe manipulation in Extra Golems, especially not that of another mod.

**Comment by AveryCorvus** [comment]
I don't believe it's recipe manipulation, I think the "raw ore block" tag is being mistakenly applies to the raw ore, since the tinker's recipe is simply calling for all "raw iron ore block" tagged items from the forge ore dict.

There's a bunch of code in Extra Golems related to retrieving and appending raw ore block tags, maybe there's something in there. But it's literally only a problem with just these mods installed and not Tinker's alone.

I'll try to pull more relevant details from CraftTweaker later, after work.

**Comment by skyjay1** [comment]
There are some block and item tags that involve raw ores, probably left over from early 1.16 before Forge added them officially. I'll see if that does anything.

**Comment by skyjay1** [comment]
Confirmed bug, thank you for the further explanation. I will revisit the item and block tags and release a fix soon :)
