### ISSUE TITLE
1.19.2 Golems constantly spawning

### ISSUE THREAD

**Issue by Kitthaven** [MinecraftModDevelopment/Extra-Golems#105]
Hello! I'm using the 1.19.2 version of the mod and settled near a Minecraft village to play Minecolonies. I noticed there were tons of clay golems everywhere in the village. I started getting some lag so I went to the village and saw the number of golems had grown out of control lol. I used a command to kill them but then within a few in-game days they were everywhere again. I just did another kill command as I started lagging again and there were 126 haha. I assume this isn't intended behaviour so thought I'd report it. (Image attached but this wasn't even half of them lol)

![2022-08-20_15 13 17](https://user-images.githubusercontent.com/50052152/185764398-2da51325-cf21-4c1a-937d-f71c7f4d1ec4.png)

**Comment by skyjay1** [comment]
Thanks for the report, you can reduce or turn off villager summon chance in the config for now
