### ISSUE TITLE
[1.19.2] [mekanism compatibility] Causes a conflict with ores multiply by 1:12 instead of 3:4

### ISSUE THREAD

**Issue by FrederickEngelhardt** [MinecraftModDevelopment/Extra-Golems#107]
Replication steps:

1. Download [mekanism ](https://www.curseforge.com/minecraft/mc-mods/mekanism), [mekanism-generators](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators), [mekanism-tools](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools) and **extra-golems** mod using forge 43.1.1 or higher. Latest should be 43.1.1 but I can replicate it on latest update of mekanism 1.19.2-10.3.2.469 and 
1. Put "raw iron" or "raw gold" in an enrichment chamber.
1. Get 12 iron|gold dust back when it should require 3 raw iron and output 4 iron dust

Original issue was submitted on the mekanism issues repo [here](https://github.com/mekanism/Mekanism/issues/7596)

**Comment by skyjay1** [comment]
I thought I fixed this in #101 :(

**Comment by FrederickEngelhardt** [comment]
@skyjay1 please reference this comment. I think this may be the fix that is required. https://github.com/mekanism/Mekanism/issues/7596#issuecomment-1229489121

Edit: nevermind see the PR reference. Thanks!
