### ISSUE TITLE
Bugged UI on a Guide Book Item's Page

### ISSUE THREAD

**Issue by LolJohn11** [MinecraftModDevelopment/Extra-Golems#108]
**Bug description:**
When opening the Extra Golems Guide item on pages 5-6, the UI gets bugged. The buttons remain in their intended places (as indicated by their sprites switching to the "hover" state correctly), but the sprites themselves are displayed incorrectly.
All of the other pages of the book display normally without the bug occurring.
I've tested it on an instance with no other mods, so this is not a mod compatibility issue.

**Platform info:**
MC 1.19.2
Forge 43.1.43
Extra Golems 19.2.3

**Screenshot of the bug:**
![2022-10-19_18 10 22](https://user-images.githubusercontent.com/49366383/196734137-d331c04c-3cdf-4344-a0f7-8c6edd0886ab.png)

**Comment by skyjay1** [comment]
I can't tell you how many times I've tried to fix this. Every time I change something in the GUI I cry.

However, your screenshot uses a different GUI scale and gives me new information, maybe I will find a fix after all.

**Comment by LolJohn11** [comment]
I am sorry for your pain.
But I hope that you will eventually manage to overcome this bug and fix it.
And the screenshot was taken at GUI Scale = 2, figured I should write this here just in case.
