### ISSUE TITLE
Golems turn to clay in version 19.2.4

### ISSUE THREAD

**Issue by MC-Watts** [MinecraftModDevelopment/Extra-Golems#113]
With due time all of the golems in the village will eventually turn to clay. The hay golems that we keep in our farms turn to clay, all the golems that spawn in the village naturally turn to clay, any golems we spawn via commands will also eventually turn to clay. We disabled clay golems from spawning in the village via the mods config file and this worked for a short while but upon restarting the server the golems all were clay again. We do not have the mod It Takes a Pillage and never have and are aware that it can cause issues. I have attached a screenshot of all of our mods as well as I assume you will likely need this for reference. 
![Mod list 3](https://user-images.githubusercontent.com/123892815/215344140-11006636-685e-4eab-a63a-28962747f27b.jpg)

**Comment by leterio** [comment]
Additional Informations for this issue:

Golem is loaded with "empty" informations (as shown in the log):

[10:46:00] [Render thread/ERROR] [golems/]: Missing golem_model for golem with ID 'golems:empty'

![image](https://user-images.githubusercontent.com/15060358/220363212-09c7e9d2-6bdd-421d-a09b-e4ec430a6a96.png)

The issue can be reproduced running from the src (master-1.19) (cf57ed6d48b1c9a2e0a61a366fc3a602218c709a)

**Comment by BadNerdCreating** [comment]
This has happened for me as well with 19.2.4. I made a copper and thatch golem and they both turned into clay golems. They have the same health but they are now clay.

**Comment by leterio** [comment]
I found the issue, fixed it at a fork.
Awaiting PR review.

**Comment by skyjay1** [comment]
Fixed in 19.2.5

**Comment by skyjay1** [comment]
My apologies to leterio, your PR came in just as I was finished re-writing the whole system 😓
