### ISSUE TITLE
Golems from Extra Golems have a taller hitbox than vanilla Iron Golems

### ISSUE THREAD

**Issue by Chachavo** [MinecraftModDevelopment/Extra-Golems#114]
Minecraft 1.19.2
Mod version 19.2.4
As the title says the golems the mod adds have a taller hitbox than the Iron Golem from vanilla.
Not very important but I noticed it.

![2023-04-26_11 44 57](https://user-images.githubusercontent.com/131740687/234646253-e270308d-dd06-4a65-89e4-5da3e4dff555.png)

**Comment by skyjay1** [comment]
Oh wow, how long has that been the case? I haven't touched any of the entity type stuff for years 😅

**Comment by Chachavo** [comment]
It seems in 1.9 iron golems were made shorter (from 2.9m to 2.7m)
