### ISSUE TITLE
The mod's golems' waists are smaller than Vanilla Iron Golems'

### ISSUE THREAD

**Issue by Chachavo** [MinecraftModDevelopment/Extra-Golems#115]
This is a really petty thing.
I noticed they have different sized waists
![image](https://user-images.githubusercontent.com/131740687/235282803-2add3cf8-d294-4c44-a775-f1e0f38f365e.png)
![image](https://user-images.githubusercontent.com/131740687/235282845-69f9cb93-5922-4c5e-bf48-30d12f61e9b5.png)
Note the vines do have the same size, but the golems from the mod have their waists scaled down a little bit.
The upper pixel in the vanilla golem's waist is half inside its torso, while the mod's golems' aren't.
It's more clear when seeing inside
![2023-04-28_23 02 28](https://user-images.githubusercontent.com/131740687/235282931-c76e2cd7-6569-4341-b9cf-b1592fa90046.png)
![2023-04-28_23 02 36](https://user-images.githubusercontent.com/131740687/235282940-0c30cf91-74cc-4bfd-87b7-9ce5e802fa80.png)
As well as when seeing it from the side
The vanilla golem's waist bulges over its legs
![2023-04-28_23 00 26](https://user-images.githubusercontent.com/131740687/235283028-3575c166-35eb-403f-856e-c99da5f60bed.png)
![2023-04-28_23 00 20](https://user-images.githubusercontent.com/131740687/235283036-dd89ec8d-797a-4b2e-8f9d-3c2b31b7bfe0.png)
I couldn't help but notice they looked slimmer than the Iron Golems

**Comment by skyjay1** [comment]
I currently use a custom model for the golems. Matching the Iron Golems 1:1 is not a priority, but thanks for pointing it out so I could think it over :)
