### ISSUE TITLE
Dispenser Crash

### ISSUE THREAD

**Issue by WenXin20** [MinecraftModDevelopment/Extra-Golems#120]
```
Minecraft v1.19.2
Forge v43.2.3
Extra Golems v19.2.6
```

After updating to the latest version, my server crashed during load. It seems like it might be related to the dispenser and spawn eggs.
[Crash Report](https://gist.github.com/WenXin20/1a7fecfbfc10d92d6545121e9b90bc30#file-extra_golems_crash-txt-L45)

**Comment by WenXin20** [comment]
Although it does not seem to have crashed the second time loading it with no changes made,

**Comment by skyjay1** [comment]
It looks like you installed too many mods that add spawn eggs and some internal cap was reached. I do not see anything in the crashlog to indicate that Extra Golems is the culprit.

**Comment by WenXin20** [comment]
yeah, odd. I haven't had the crash since
