### ISSUE TITLE
Wool golems trigger sculk sensors

### ISSUE THREAD

**Issue by Chachavo** [MinecraftModDevelopment/Extra-Golems#122]
It would be expected that wool golems would not make vibrations since wool occludes them.

**Comment by dshadowwolf** [comment]
...
You know, I generally don't comment on anything here, but... This gets an upvote from me - it really does seem like the proper thing. If players walking on wool doesn't trigger sculk sensors, then a golem _made_ from the stuff shouldn't either.

**Comment by skyjay1** [comment]
A+ suggestion, almost as good as the suggestion to make golems [wear banners as capes](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues/39#issuecomment-782757143)

**Comment by skyjay1** [comment]
Fixed in 20.1.0.0
