### ISSUE TITLE
cant make golems 1.20.1

### ISSUE THREAD

**Issue by mrman145** [MinecraftModDevelopment/Extra-Golems#131]
when i place the golem head on the golem body it is not making a golem

**Comment by skyjay1** [comment]
Please share a screenshot and a list of all other mods you have installed

**Comment by mrman145** [comment]
![image](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/assets/163067204/d3305240-7307-4ae7-b4d0-8fc4f538d0bd)

the ones that are white are disabled

**Comment by mrman145** [comment]
dose this work

**Comment by Moses24713** [comment]
I've run into the same issue, I also cant summon them with commands

**Comment by Moses24713** [comment]
Pretty sure it's a problem with Apotheosis, I got this from the logs when trying to make a golem https://pastebin.com/4RF5B3ZX

Edit: After temporarily removing Apotheosis and its addons from my pack it now works hopefully there is an easy patch to fix this so we can play with both mods

**Comment by skyjay1** [comment]
Related to #109

**Comment by skyjay1** [comment]
Fixed in Extra Golems 20.1.0.2 (pending approval on CurseForge)
