### ISSUE TITLE
All Golems Are Invisible

### ISSUE THREAD

**Issue by BudderyShloofy** [MinecraftModDevelopment/Extra-Golems#134]
So essentially for whatever reasons every golem spawns in invisible, I am not sure why but for context I'm on a server on 1.20.1 and I do have quite a few other mods installed, however, if it is an issue between mods, I have no idea which mod would be making them invisible. Are there any known problems with other mods? is this a bug that is already known? any info would help as I would like to keep this mod on my server.

**Comment by skyjay1** [comment]
Are you using Extra Golems 20.1.0.2?

**Comment by BudderyShloofy** [comment]
No, I seem to be using 20.1.0.0. I will try updating it and get back to you!

**Comment by BudderyShloofy** [comment]
This seems to fix it, kind of my bad for not realizing it needed to be updated lol. Thanks!
