### ISSUE TITLE
Crash with Ice and Fire's Myrmex

### ISSUE THREAD

**Issue by BugmanBugman** [MinecraftModDevelopment/Extra-Golems#23]
https://paste.dimdev.org/ledibahesa.mccrash

Happened out of no where. I was just approaching a hive and it crashed.

**Comment by skyjay1** [comment]
Looks like a village-like structure was generated, triggering automatic golem spawning. It's probably because the biome isn't one I checked for, should be a simple fix. For now you should turn off the config option that spawns golems in villages

**Comment by skyjay1** [comment]
Fixed in Build 7.1.4
