### ISSUE TITLE
Forge tags compatibility

### ISSUE THREAD

**Issue by thinkverse** [MinecraftModDevelopment/Extra-Golems#30]
I had a comment on my mod about storing the Golem book in my bookshelfs, so I thought, why don't you add the book to forge tags? under **forge/tags/items/books** and the paper under **forge/tags/items/paper** ? seems like a smart idea to have books and papers under forge tags for mod compatibility.

Just a thought, as for now I'm suggesting people to add items under a datapack, but this seems like a better option for compatibility between mods.

**Comment by TheGlitch76** [comment]
See 0dba4ea750033f8034dab42c61313493bd79c6fc
