### ISSUE TITLE
Golem Health Indicator

### ISSUE THREAD

**Issue by Meskino** [MinecraftModDevelopment/Extra-Golems#33]
A new option to see the golem health with cracks in their skin  like anvil states
![damaged iron golem indicator](https://user-images.githubusercontent.com/33664951/61939139-97cc9880-af60-11e9-9961-322fe366ef5e.png)
That would be the suggestion more than anything, I think you've already heard it on several sides but I suggest it anyway.

**Comment by skyjay1** [comment]
Added to the next release of Extra Golems for 1.14
Thanks for the great ideas!
