### ISSUE TITLE
Add option to disable golems setting villages as their homes

### ISSUE THREAD

**Issue by EricChelmu** [MinecraftModDevelopment/Extra-Golems#34]
When I create a golem, it automatically runs to the nearest village. I also have mo villages mod installed, but I don't think that is a problem.

**Comment by TheGlitch76** [comment]
How "near" is "nearest"?
Are we talking within your render distance (~10 chunks if on a dedicated server) or a few minutes away?

**Comment by TheGlitch76** [comment]
Also, are you on 1.12.2 or the latest version?

**Comment by EricChelmu** [comment]
I am on 1.12.2 and near is like, 20-30 blocks away, and i have my render distance on 12 chunks, so yeah, it is in the render distance. They just run there, if I don't tie them to a fence with a lead.

**Comment by skyjay1** [comment]
That is correct. Golems search for villages and make them their home. When created, the golem looks for a village within 128 blocks, and if none is found, it continues searching while wandering around a 64-block radius.
Is the issue that you would like to disable this behavior? If so, we can add a config option to turn it off or to restrict the search radius, but either one may affect golem behavior once they are inside a village.

**Comment by EricChelmu** [comment]
I wouldn't necessarily disable the behavior, but if it's the only way I can keep the golems at my house then yes, i would disable it. I usually just steal stuff from the villages so it wouldn't bother me much, if their behaviour would be changed inside a village.

**Comment by skyjay1** [comment]
Closing as we no longer have direct control over the way that golems set their homes.
