### ISSUE TITLE
No data fixer registered

### ISSUE THREAD

**Issue by bloodconfetti** [MinecraftModDevelopment/Extra-Golems#35]
I'm not sure how much this matters, but in my latest log, there are several warnings for not having a data fixer registered for the golems.
[latest.log](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/3493346/latest.log)

**Comment by TheGlitch76** [comment]
I'll take a look at if this is an issue.

**Comment by TheGlitch76** [comment]
This doesn't seem to be an issue when upgrading from 1.12 (which is what datafixers are for).
Closing this issue for now.
