### ISSUE TITLE
1.14 server crash

### ISSUE THREAD

**Issue by skyjay1** [MinecraftModDevelopment/Extra-Golems#36]
nmdchiri wrote:

I can't seem to make a server with this mod. I tried adding only this mod on forge 1.14.4-28.0.45 and it gave me this crash report:

---- Minecraft Crash Report -------- Minecraft Crash Report ----// I just don't know what went wrong :(
Time: 10/08/19 23:42Description: Exception in server tick loop
net.minecraftforge.fml.LoadingFailedException: null at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:198) ~[?:?] {} at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:186) ~[?:?] {} at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:907) ~[?:?] {} at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:186) ~[?:?] {} at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {} at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A} at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- System Details --Details: Minecraft Version: 1.14.4 Minecraft Version ID: 1.14.4 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_211, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 1516288912 bytes (1446 MB) / 2138570752 bytes (2039 MB) up to 4772593664 bytes (4551 MB) CPUs: 8 JVM Flags: 2 total; -Xms512M -Xmx5G ModLauncher: 3.2.0+60+b86c1d4 ModLauncher launch target: fmlserver ModLauncher naming: srg ModLauncher services:  /eventbus-0.10.6-service.jar eventbus PLUGINSERVICE  /forge-1.14.4-28.0.45.jar object_holder_definalize PLUGINSERVICE  /forge-1.14.4-28.0.45.jar runtime_enum_extender PLUGINSERVICE  /accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE  /forge-1.14.4-28.0.45.jar capability_inject_definalize PLUGINSERVICE  /forge-1.14.4-28.0.45.jar runtimedistcleaner PLUGINSERVICE  /forge-1.14.4-28.0.45.jar fml TRANSFORMATIONSERVICE  FML: 28.0 Forge: net.minecraftforge:28.0.45 FML Language Providers:  javafml@28.0 minecraft@1 Mod List:  extragolems-9.0.0-beta.jar Extra Golems {golems@TODO-golems_version ERROR} forge-1.14.4-28.0.45-universal.jar Forge {forge@28.0.45 LOAD_REGISTRIES} forge-1.14.4-28.0.45-server.jar Minecraft {minecraft@1.14.4 LOAD_REGISTRIES} Data Packs:  Is Modded: Definitely; Server brand changed to 'forge' Type: Dedicated Server (map_server.txt)

Thanks in advance! I love your mod, thanks for all the hard work!
(Source: [CurseForge.com](https://www.curseforge.com/minecraft/mc-mods/extra-golems#c169))

**Comment by skyjay1** [comment]
realnerdyviking said:

I'm having the same issue as nmdchiri.

 

I love this mod as it makes city building and village building much cooler at endgame and it also makes hard significantly less taxing on defending villages. I have been trying to get this to work on my server with the newest forge version (as of 21-august) and it keeps crashing. In the interest of being as helpful as possible...I have also included my crash report. I hope you can fix this soon, and thank you already for all your hard work! =]

 

Spoiler (click to hide)
---- Minecraft Crash Report -------- Minecraft Crash Report ----// Oh - I know what I did wrong!
Time: 8/21/19 10:33 AMDescription: Exception in server tick loop
net.minecraftforge.fml.LoadingFailedException: null at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:198) ~[?:?] {} at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$24(ModLoader.java:186) ~[?:?] {} at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:907) ~[?:?] {} at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:186) ~[?:?] {} at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {} at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A} at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] {}

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- System Details --Details: Minecraft Version: 1.14.4 Minecraft Version ID: 1.14.4 Operating System: Linux (amd64) version 4.9.177-xxxx-std-ipv6-64 Java Version: 1.8.0_181, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 3118853656 bytes (2974 MB) / 3675783168 bytes (3505 MB) up to 7635730432 bytes (7282 MB) CPUs: 12 JVM Flags: 4 total; -Xmx8192M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512 ModLauncher: 3.2.0+60+b86c1d4 ModLauncher launch target: fmlserver ModLauncher naming: srg ModLauncher services:  /eventbus-0.10.6-service.jar eventbus PLUGINSERVICE  /custom.jar object_holder_definalize PLUGINSERVICE  /custom.jar runtime_enum_extender PLUGINSERVICE  /accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE  /custom.jar capability_inject_definalize PLUGINSERVICE  /custom.jar runtimedistcleaner PLUGINSERVICE  /custom.jar fml TRANSFORMATIONSERVICE  FML: 28.0 Forge: net.minecraftforge:28.0.55 FML Language Providers:  javafml@28.0 minecraft@1 Mod List:  AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 LOAD_REGISTRIES} AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 LOAD_REGISTRIES} branders-lampblock-v1.1.1-1.14.4.jar Lamp Block Mod {lampblockmod@1.1.1 LOAD_REGISTRIES} ClassicCombat-1.14.3-1.0.0-universal.jar Classic Combat {classiccombat@1.0.1 LOAD_REGISTRIES} create-mc1.14.4_v0.0.5.jar Create {create@0.0.5 LOAD_REGISTRIES} DoggyTalents-1.14.4-1.15.1.3-universal.jar Doggy Talents {doggytalents@1.15.1.3 LOAD_REGISTRIES} extlights-1.2.jar Extended Lights {extlights@1.2 LOAD_REGISTRIES} extragolems-9.0.0-beta.jar Extra Golems {golems@TODO-golems_version ERROR} FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 LOAD_REGISTRIES} forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 LOAD_REGISTRIES} furniture-7.0.0-pre5-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre5 LOAD_REGISTRIES} gravestone-1.15.0.jar Gravestone Mod {gravestone@1.15.0 LOAD_REGISTRIES} LightOverlay-3.4.jar Light Overlay Forge {lightoverlay-forge@3.4 LOAD_REGISTRIES} lycanitesmobs-1.14.4-2.1.0.0-beta17.jar Lycanites Mobs {lycanitesmobs@1.0 LOAD_REGISTRIES} MineMenu-1.14.4-1.8.2.jar MineMenu {minemenu@1.14.4-1.8.2 LOAD_REGISTRIES} playerplates-1.14.4-forge-1.1.0.jar Player Plates {playerplates@1.14.4-forge-1.1.0 LOAD_REGISTRIES} practicaltools-1.14.4-1.4.jar Practical Tools {practicaltools@1.14.4-1.4 LOAD_REGISTRIES} switchbow-1.5.7.jar Switch-Bow {switchbow@1.5.7 LOAD_REGISTRIES} u_team_core-1.14.4-2.7.0.129.jar U Team Core {uteamcore@2.7.0.129 LOAD_REGISTRIES} useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 LOAD_REGISTRIES} wildnature-2.0.0+ALPHA.jar WildNature Mod {wildnature@1.3 LOAD_REGISTRIES} forge-1.14.4-28.0.55-universal.jar Forge {forge@28.0.55 LOAD_REGISTRIES} forge-1.14.4-28.0.55-server.jar Minecraft {minecraft@1.14.4 LOAD_REGISTRIES} Data Packs:  Is Modded: Definitely; Server brand changed to 'forge' Type: Dedicated Server (map_server.txt)

**Comment by TheGlitch76** [comment]
Fixed in 68fda26d004c6b1f5fc0c3079cf448b1a51464bc
