### ISSUE TITLE
[1.14.4] Random crash (ticking entity?)

### ISSUE THREAD

**Issue by Gbergz** [MinecraftModDevelopment/Extra-Golems#43]
Heya, was playing around w/ your mod installed and i got this random crash while i was inside a Village.

MC-Ver: 1.14.4
Mod-Ver: 9.0.2
Forge-Ver: 28.1.44

CRASH-REPORT: [https://gist.github.com/Gbergz/19a412187b57847be1810bb033292e27](https://gist.github.com/Gbergz/19a412187b57847be1810bb033292e27)

**Comment by skyjay1** [comment]
See issue #38 and workaround solution posted
