### ISSUE TITLE
Swimming Golems crash in villages

### ISSUE THREAD

**Issue by skyjay1** [MinecraftModDevelopment/Extra-Golems#46]
Versions 1.14.x and 1.15.x
Crash occurs when a Coral or Sea Lantern golem enters a village while swimming. The issue is that a Goal inherited from Iron Golem does an unsafe cast. Not sure how to fix it.

`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/1/20 9:58 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.pathfinding.SwimmerPathNavigator cannot be cast to net.minecraft.pathfinding.GroundPathNavigator
	at net.minecraft.entity.ai.goal.MoveThroughVillageGoal.shouldExecute(MoveThroughVillageGoal.java:72) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.shouldExecute(PrioritizedGoal.java:25) ~[?:?] {re:classloading}`

**Comment by minecraftgreat123** [comment]
This kept happening as I make a coral golem to swim in the ocean by a village and it kept crashing.
AT first, I thought was my computer. Then, I  relauched my modpack, it was work normally then repeat the same process create a coral golem, and sea lantern. My modpack freezed and crashed so im like this has to be a bug
