### ISSUE TITLE
Make golems passive towards the player who created them

### ISSUE THREAD

**Issue by GuichoSax** [MinecraftModDevelopment/Extra-Golems#47]
Minecraft Version: 1.15.2
    Forge Version: 31.0.16
    Mod Version: Extra Golems 10.0.0-beta
    Java Version: 8 Update 241 (64 bit)
    Operating System (OS): Windows 10 Home 64-bit.
    Aternos multiplayer (private) server.

Issue Description:
Any crafted Extra Golem spawns as a Neutral mob, attacking any hostile mob but also attacking the player if accidentally hit.

Steps to reproduce:
    Craft an Extra Golem (any kind)
    Approach it and hit it with bare hand or anything on hotbar
    The Extra Golem will take you as Hostile and hunt you until it kills you.
    Cry

Additional Information:
Extra Golems are currently behaving like Vanilla Iron Golems that you naturally encounter, where I think they should be behaving like Vanilla Iron Golems but that you craft, where no matter how/if you hit them, they will always be loyal to you and not hitting back because you created them.
This happened by digging dirt with a shovel and accidentally hitting a Glass Golem, the jumpscare was real.
Then I get into the task of crafting and hitting every single Extra Golem and I sadly confirm everyone is "Neutral", attacking you back.
We're scared of our own Extra Golems!

Thank you very much for taking the time to look this up! <3

**Comment by skyjay1** [comment]
Thank you for the detail. Luckily this is a very easy fix on your end because the config file includes an option to prevent "friendly fire". Let me know if you have trouble finding the config or if changing the value does not fix the issue.

**Comment by GuichoSax** [comment]
Thank you very much!! I'll leave a note below just in case somebody sees this report and have no clue finding the .toml file.

How to find:
world save > serverconfig > golems-server.toml
#When enabled, attacking a player-built golem will make it attack you
friendly_fire =  true
Setting this value to false will prevent your own golems from attacking player.
