### ISSUE TITLE
korean language support(for ver 10.1.0)

### ISSUE THREAD

**Issue by MilkissWhite** [MinecraftModDevelopment/Extra-Golems#48]
I tried to translate all string. but I don't using Waila so I coudn't check some strings.

[ko_kr.zip](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/4340595/ko_kr.zip)

I hope this will be helpful.

**Comment by skyjay1** [comment]
Thank you! I will add this to the 1.14 and 1.15 branches of the mod.
