### ISSUE TITLE
Config file missing?

### ISSUE THREAD

**Issue by ghost** [MinecraftModDevelopment/Extra-Golems#50]
Hello!

I'm having an issue actually finding the config file. For all my other mods they're in \Roaming\.minecraft\config, but I can't seem to find it for Extra Golems. Is it not automatically generated when running the game for the first time using the mod? (the mod appears in my Mod menu)

Tried looking one by one through all my config folder but without success.

I am on 1.52.2 version and forge 31.1.70.
I'm attaching a screenshot with the content of my config folder (I have around 90 mods installed).
![Clipboard01](https://user-images.githubusercontent.com/17991705/82569019-51e45f00-9b88-11ea-9b76-3d56ad12926d.jpg)

**Comment by skyjay1** [comment]
In Forge 1.14+ config files are saved per-world. To find the config for this mod go to your .minecraft folder (if using Windows, go to %appdata% to get there). Click on "saves", select the name of the world, and go into "serverconfig". There you will find a file named "golems-server.toml" which is the config file for this mod. Hope that helps
![image](https://user-images.githubusercontent.com/15920401/82977227-797b6300-9f9e-11ea-84c5-193815679c57.png)

**Comment by skyjay1** [comment]
Config is now common instead of server-only
