### ISSUE TITLE
Can't unistall from world

### ISSUE THREAD

**Issue by stonemandave** [MinecraftModDevelopment/Extra-Golems#53]
When ever i delete the mod i get the datapack error when i load up.

**Comment by TheGlitch76** [comment]
Please upload a crashlog to a site like [pastebin](https://pastebin.com/) and post it here.

**Comment by stonemandave** [comment]
https://pastebin.com/WjdWifvQ

doesn't crash because it doesn't load.

**Comment by skyjay1** [comment]
1. If you are getting an error that says "Forge Mod Loader detected missing registry entries" when you open the save file and attempt to load a world, this is normal when removing a mod. You may proceed.
2. If you are getting some other error or are unable to load the world, it may be related to a Mr Crayfish Vehicle Mod according to line 676 of the report you posted.

**Comment by stonemandave** [comment]
So i should be able to uninstall without the safe mode screen popping up this is new to me and the reason I want to uninstall because the villagers doesn't spawn any iron golem

**Comment by stonemandave** [comment]
You were correct sir i can load if i remove mcvehicles and yours at the same time thanks for the help.
