### ISSUE TITLE
Iron Golem does not spawn after uninstalling mod

### ISSUE THREAD

**Issue by stonemandave** [MinecraftModDevelopment/Extra-Golems#55]
After I uninstalled iron golem no longer spawn or can be made by the player any help will be greatly appreciated and thanks for the mod.

https://drive.google.com/file/d/1syD-VYm7-ZiVAwWbMScjOh7YNj-AfdQm/view?usp=sharing

**Comment by skyjay1** [comment]
It's literally impossible for me to affect the game if the mod is uninstalled, at least on purpose. Since the current build is beta I'm sure there could be many other things going on to cause this, so I'm going to release a (hopefully) more stable build this weekend and you can let me know if you have the same problem then.
It is advised to start a new world when adding or removing mods for this reason.

**Comment by stonemandave** [comment]
Makes sense when dealing with mods but could you tell me how to get the villagers to generate iron golems because non generate in my iron farm if I can get 10 iron golems to 1 extra golem I would be ecstatic. and I will be more than willing to test things for you.

**Comment by skyjay1** [comment]
To reduce the number of Extra Golems that are summoned by villagers, change the config setting:
`#Percent chance for a villager to successfully summon an Extra Golems golem`
`#Range: 0 ~ 100`
`villager_summon_chance = 10`

**Comment by stonemandave** [comment]
OK, I have done some testing I got the iron golems to spawn from me but not the villagers I.m a 100% sure I broke something but not your fault I will figure out what happened to the villagers not being able to spawn iron golems. And I can't get them to spawn iron plate golems from modifying the config if I can get that to work I will be golden.

**Comment by walker40061** [comment]
> OK, I have done some testing I got the iron golems to spawn from me but not the villagers I.m a 100% sure I broke something but not your fault I will figure out what happened to the villagers not being able to spawn iron golems. And I can't get them to spawn iron plate golems from modifying the config if I can get that to work I will be golden.

I'm having the same problem. Were you able to find a fix. If yes then please let me know
