### ISSUE TITLE
Invisible Golems

### ISSUE THREAD

**Issue by UserT** [MinecraftModDevelopment/Extra-Golems#57]
Extra-Golems seem to work - it looks like they should be created - but after I place the head they disappear or are invisible.
Using /summon golems: to spawn them also seems to work but nothing appears.
Creating regular iron golems still works though.

MC Version: 1.16.2
Forge Version: 33.0.20
Extra-Golems Version: 11.1.3

**Comment by skyjay1** [comment]
I was unable to reproduce the bug using Forge 33.0.22.

Are you using other mods? It sounds like a rendering issue, so mods that affect rendering may be interfering.

Are you using a dedicated server? I was unable to test on a server in my build environment.

Is there anything unusual in the logs? When building an Extra Golems golem, a log entry will appear with something like: 
`Building golem GenericGolem['Clay Golem'/589, l='ServerLevel[Golems-test-1.16 (2)]', x=-694.50, y=64.05, z=463.50]` 
Do you see any errors immediately after that?

**Comment by UserT** [comment]
Yeah I have some mods running.
Server side I have:
Oh the Biomes you'll go 1.0.2
extragolems 11.1.3
gravestone 1.0.4
mahoutsukai 1.21.8
repurposed_structures 2.1.0

I will throw the log file in here too. I did notice '[modloading-worker-1/ERROR] [net.minecraft.util.Util/]: No data fixer registered for golem_TYPEHERE' sorts of error.
[latest.log](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/5144725/latest.log)

In the meantime I'll try to remove any rendering stuff client side to see if that fixes it. Thanks for looking into it.

**Comment by UserT** [comment]
I have a little more info - not sure it will be helpful or not.
My original report was in a multiplayer server. If I join a single player world first - then exit the world - and join the server the mod works great.

**Comment by skyjay1** [comment]
~~I noticed this in the log:~~
~~`[28Aug2020 10:44:20.834] [Server thread/INFO] [golems/]: [Extra Golems]: Building golem BookshelfGolem['Librarian Golem'/2899, l='ServerLevel[world]', x=122.50, y=70.05, z=-38.50]`
`[28Aug2020 10:52:46.133] [Netty Server IO #4/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.ModIdArgument@d182c1c (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!`
`[28Aug2020 10:52:46.135] [Netty Server IO #4/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.EnumArgument@538c4836 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!`~~
Edit: the above log is not the problem.
I'm not sure what's going on, to be honest. Maybe the server and client have different versions of the mod or are using different versions of Forge?

**Comment by drakray** [comment]
Hi there, I can confirm, in MC 1.16.3, Forge 34.1.19, ExtraGolem 11.1.4, plus bunch of others, that EG Golems are invisible, without hitbox(F3+B), when connecting directly to a Multiplayer server with the same setting.

Opening a Solo game before seems to fix this, as I connected to my server after and saw that the village I settled in was not protected by a single IronGolem, but in fact by about 5 EG Golems lol

I also saw the multiple New golem I made before, so maybe it's a sync problem?

**Comment by skyjay1** [comment]
I have tested this on a dedicated server and confirmed that this bug exists, even when the only mod installed is Extra Golems. I'm going to have to figure out what's causing it, because as of now I have no leads...

**Comment by drakray** [comment]
@skyjay1 I'm throwing an idea randomly, could it be the way they are registered?
In Single Player, both Client- and Server- Side are loaded, but when connecting on a server only Client is, maybe there is something in this way since when going Solo before Multi, Golems are visible?
On the Server they exist even though they are invisible, because they can get killed by mobs, and drop their Golem Spell and resources

Or maybe I'm completely off-track :/

**Comment by skyjay1** [comment]
@drakray You were close. It turns out that storing all the golem stats (health, attack, etc) in the config was only being done server-side. Which means that when golems were registered, only the server thought they were registered correctly.
I'll upload the fixed build right away.

**Comment by drakray** [comment]
yay, I might've helped slightly \o/
