### ISSUE TITLE
Some textures of the golem look weirder than before

### ISSUE THREAD

**Issue by BugmanBugman** [MinecraftModDevelopment/Extra-Golems#59]
I believe this is due to pulling from the current texture pack
Before
![image](https://user-images.githubusercontent.com/40730042/96635731-e393fc00-12e1-11eb-939a-204f1efa3122.png)
After
![2020-10-20_19 21 57](https://user-images.githubusercontent.com/40730042/96635759-e989dd00-12e1-11eb-9921-ba2d2d8d83f8.png)

**Comment by TheGlitch76** [comment]
Yes. this is how generated vs. custom textures work.

**Comment by BugmanBugman** [comment]
Ah yes. Is there any option to switch back to custom textures?

**Comment by skyjay1** [comment]
There is not an in-game option but I may make a texture pack available with all the old hand-made textures.
