### ISSUE TITLE
Toolsmith Villagers being VERY loud while repetitively attempting to repair an Extra Golem

### ISSUE THREAD

**Issue by MarioMario24680** [MinecraftModDevelopment/Extra-Golems#65]
Hi, in the most recent version of Extra Golems on my Minecraft 1.16.4 server (Forge 35.1.13), there's a strange bug where there's loud, repetitive banging noises coming from Villagers trying to fix up a non-iron-based golem. I don't have any audio files to give you, but if you try spawning a bunch of villagers and assign them to the Toolsmith profession, you can hear it for yourself if you wait long enough for the golems to get damaged somehow. Here's a screenshot of them being stuck in the same position through multiple days and nights: https://prnt.sc/w8v04r

Extreme case with almost 10 Villagers attempting to repair a golem: https://prnt.sc/w8yg8b

The only things that can stop the loop are introducing a hostile mob which sends the Villagers into a panicked state or killing the villagers/golem yourself.

**Comment by skyjay1** [comment]
Welp, I guess Mojang never guessed that I would subclass IronGolemEntity and *not* let it be healed with iron. I'm not sure how to fix this.

**Comment by skyjay1** [comment]
The bug has been traced down to the Guard Villagers mod (not Mojang). Unfortunately the Issues section of their github seems pretty neglected, so it's unlikely this will be fixed any time soon.

**Comment by seymourimadeit** [comment]
guard villagers creator speaking here : i will fix it when i get time, i've been focusing on schoolwork alot lately, the fix is just making it so clerics check for only iron golems and not anything that extends from it.

**Comment by skyjay1** [comment]
@seymourimadeit much appreciated, I'm also in the middle of school so I completely understand :) good luck!

**Comment by skyjay1** [comment]
Guard Villagers has a release dated Feb 15, this should be fixed in that version
