### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by 48004800** [MinecraftModDevelopment/Extra-Golems#67]
1 golem_dispenser   You can set the arrow to damage only some kinds of entities.
By judging the attack target of the entity, the hostile entity can be distinguished well
This is compatible with other mods.

2 Golems The puppet should have a better attack target system, and judge whether to attack the entity through the attack targets of other entities.  In this way, the puppet will not be beaten passively. He can identify the target through better mechanism.

**Comment by 48004800** [comment]
I don't seem to express myself clearly . In short, golems can judge whether it is a hostile entity according to the attack target of other entities

**Comment by skyjay1** [comment]
Please add these to #39 so all of the suggestions are in one place. Thank you :)

**Comment by skyjay1** [comment]
Merged with #39
