### ISSUE TITLE
Extra Golems Crash with Quark

### ISSUE THREAD

**Issue by spindisc** [MinecraftModDevelopment/Extra-Golems#68]
Not sure what happens, but it seems Quark is doing something with stone types that Extra Golems don't like.
[crash-2021-01-30_22.25.36-fml.txt](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/5898757/crash-2021-01-30_22.25.36-fml.txt)

**Comment by skyjay1** [comment]
Looks like Quark moved some things around again, please use an older version of Quark until I get this fixed.

**Comment by skyjay1** [comment]
Actually, it looks like you're using an old version of Extra Golems (11.1.9) Update to the latest version (11.2.0) and this should be fixed.
