### ISSUE TITLE
compatibility with Epic Fight Mod

### ISSUE THREAD

**Issue by ekiplier** [MinecraftModDevelopment/Extra-Golems#69]
This new amazing mod was released that gives golems great animations. If this mod had compatibility with it, it would be pretty neat. The mod is [Epic Fight Mod](https://www.youtube.com/watch?v=RxzuYR_4GNg&t=134s)

**Comment by skyjay1** [comment]
Sorry, compatibility (from my side) is not an option. If the developer of the Epic Fight Mod wants to add support for Extra Golems, though, it's possible from their side.
