### ISSUE TITLE
make redstone and that magic paper as a drop disableable

### ISSUE THREAD

**Issue by 2el222** [MinecraftModDevelopment/Extra-Golems#71]
I'm not using magic paper(enabled carved pumpkin as a head in config), and it is useless and just hoards if u farm the golems, same with redstone...

**Comment by skyjay1** [comment]
The magic paper and redstone are added using loot tables and you can use a datapack to provide your own version of [_golem_base.jso](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/blob/master-1.16/src/main/resources/data/golems/loot_tables/entities/_golem_base.json)n if you don't want those items to drop.
