### ISSUE TITLE
Upside down

### ISSUE THREAD

**Issue by KhaleesiCat87** [MinecraftModDevelopment/Extra-Golems#72]
The golems from Extra golems are upside down . The regular iron golems are right side up so I don't know what's happening.

**Comment by soupcant95** [comment]
Yep, for some reason golems are upside down except their eyes.
![2021-03-30_16 40 26](https://user-images.githubusercontent.com/34650262/113016703-a6784380-9176-11eb-8274-2f8eae26574b.png)

**Comment by williambl** [comment]
https://github.com/MinecraftModDevelopmentMods/Extra-Golems/blob/master-1.16/src/main/java/com/mcmoddev/golems/renders/model/GolemModel.java#L47

Looks to be intentional. It'll go away on April 3rd. You can turn it off before then by disabling "holiday tweaks" in the config.

**Comment by skyjay1** [comment]
Looks like my April Fools prank got me instead! I'll fix it so the eyes and vines also go upside down for next year haha
