### ISSUE TITLE
Extra Golems not recognizing the latest version of Thermal Expansion

### ISSUE THREAD

**Issue by Cynix32** [MinecraftModDevelopment/Extra-Golems#76]
MC 1.16.5
Forge 36.1.13

I am not a native english speaker, The screenshot could tell more than what I can put into words:
![Screenshot (139)](https://user-images.githubusercontent.com/69455883/115989021-bd337e00-a5ee-11eb-969c-5c6f89daebb2.png)

This is the same problem as
https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry/issues/193

As you can see from the screenshot, it happens with Extra golems not recognizing thermal probably due to the "1.16.3"

**Comment by kencinder** [comment]
This is fixed in https://github.com/MinecraftModDevelopmentMods/Extra-Golems/pull/75 and is due to a Forge change.

You can edit the mods.toml in the extra golems jar for now

**Comment by skyjay1** [comment]
Yes, sorry for the inconvenience. The next release will have the updated mods.toml

**Comment by McKitten** [comment]
This fix might work for individual users but I wish to make a modpack with this included and curseforge won't accept a changed file.

It is a little extra work for you but if you could push a beta or something though with the changes it would be appreciated.
