### ISSUE TITLE
Extra Golems wont spawn naturally.

### ISSUE THREAD

**Issue by Frey74** [MinecraftModDevelopment/Extra-Golems#77]
I went to over 20 villages after installing the mod and not a SINGLE ONE had any extra golems. and for some reason I cant change the configs so I cant force the golems to spawn either

**Comment by skyjay1** [comment]
It takes some time for golems to start appearing. They can only appear if 1) a villager is in distress 2) that villager can summon a golem and 3) there are no other golems within 10 blocks.
Is everything else working correctly? The mod is properly installed?

**Comment by skyjay1** [comment]
Possibly related to #84
