### ISSUE TITLE
Healing Dispenser Golems

### ISSUE THREAD

**Issue by KnightCa** [MinecraftModDevelopment/Extra-Golems#83]
I'm unable to click on a Dispenser Golem with Dispensers or Cobblestone to heal it (it instead opens up the 3x3 box for Arrow ammunition). How do you heal a Dispenser Golem?

**Comment by skyjay1** [comment]
Try crouching while using the item on the golem.

**Comment by KnightCa** [comment]
Crouching with Cobblestone in hand and doing the following fails to heal Dispenser Golem:
- left click, hits the golem with a punch and deals damage.
- right click gives a message "You can give this golem a name tag!"

**Comment by skyjay1** [comment]
I don't remember adding any chat messages about name tags... what other mod are you using?

**Comment by KnightCa** [comment]
From the below testing and seeing how a Crafting Golem works, I believe that Dispenser Golems should work like the following:
- A damaged Dispenser Golem should be healed by right clicking with a Cobblestone or Dispenser (currently it instead opens a Storage Grid).
- Right clicking a damaged Dispenser Golem with nothing in hand should open the Storage Grid to add Arrows (currently functions like this).

Removed other mods, except for this one and Hwyla.
- Minecraft Version: 1.12.2
- Forge Version: 14.23.5.2854

Mods installed:
- ExtraGolems-1.12-7.1.9
- Hwyla-1.8.26-B41_1.12.2 (so we can see the golems health)

Steps to Replicate issue:
- Created a new Creative local world.
- Created Dispenser Golem and added 64 arrows
- Punch Dispenser Golem to give damage.
- Try to heal a damaged Dispenser Golem with Dispenser block (using right button). Storage grid opens, showing 64 arrows.
- Try to heal a damaged Dispenser Golem with Dispenser block (crouching and using right button).  Nothing happens.
- Try to heal a damaged Dispenser Golem with Cobblestone block (using right button). Storage grid opens, showing 64 arrows.
- Try to heal a damaged Dispenser Golem with Cobblestone block (crouching and using right button). Nothing happens.
- Click on a damaged Dispenser Golem with nothing in hand (using right button). Storage grid opens, showing 64 arrows.
- Click on a damaged Dispenser Golem with nothing in hand (crouching and using right button). Nothing happens.

Alternative test to make sure Healing works:
- Created Crafting Golem
- Punch Crafting Golem to give damage.
- Try to heal a damaged Crafting Golem with Craft Table block (using right button). Golem heals.
- Try to heal a damaged Crafting Golem with Craft Table block (crouching and using right button). Nothing happens.
- Try to heal a damaged Crafting Golem with Oak Planks block (using right button). Golem heals.
- Try to heal a damaged Crafting Golem with Oak Planks block (crouching and using right button). Nothing happens.
- Click on a damaged Crafting Golem with nothing in hand (using right button). Crafting table opens.
- Click on a damaged Crafting Golem with nothing in hand (crouching and using right button). Nothing happens.

**Comment by skyjay1** [comment]
Thank you for the detailed information! I'm currently working on a completely overhauled system for Extra Golems for 1.17.1 but I will add this to the list.
