### ISSUE TITLE
Villager summoning golems from config causing crash

### ISSUE THREAD

**Issue by imagelesskink** [MinecraftModDevelopment/Extra-Golems#84]
Minecraft crashes on ticking the bookshelf golem. Logs attached.
[latest.log](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/7071668/latest.log)
[debug.log](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/7071669/debug.log)

**Comment by skyjay1** [comment]
I'll look into this. For now disable villager-summoned golems in the config (set `villager_summon_chance` to `0`)

**Comment by skyjay1** [comment]
Looks like I messed up with the default configs. Notice that all the entries in `villager_summon_golems` are in the format `golems:golems:bookshelf` or whatever? Remove the extra `golems:` and you should be fine. I'll check why the config was set up to default to that.
