### ISSUE TITLE
All Golems use the "Iron Golem breaks" subtitle

### ISSUE THREAD

**Issue by Ch1216** [MinecraftModDevelopment/Extra-Golems#87]
When using subtitles when damaging/breaking any golem the subtitles use "Iron Golem breaks" subtitle

**Comment by skyjay1** [comment]
That's because I don't have custom sounds... I'll put keep this in mind but it's low priority tbh

**Comment by skyjay1** [comment]
The golems now use the same sounds as the block they are made of. There are still no custom subtitles but I do not plan to add custom sounds, so that won't be happening.
