### ISSUE TITLE
Interacting with a Golem Dispenser

### ISSUE THREAD

**Issue by BlackAures1** [MinecraftModDevelopment/Extra-Golems#88]
mcmoddev.golems.menu.PortableDispenserMenu
There was a serious crash on the server.

[crash-2021-10-02_12.06.55-server.txt](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/7271400/crash-2021-10-02_12.06.55-server.txt)

**Comment by skyjay1** [comment]
I've located the source of the crash, I'll release an update soon. I have a few changes I need to make anyway
