### ISSUE TITLE
Config is generating bad golem ResourceLocation strings

### ISSUE THREAD

**Issue by arketec** [MinecraftModDevelopment/Extra-Golems#90]
Message:
Exception caught during firing event: Non [a-z0-9/._-] character in path of location: golems:golems:bookshelf

[paste of log](https://pastebin.com/u017tLQM)

the issue it seems is located here:
https://github.com/MinecraftModDevelopmentMods/Extra-Golems/blob/e4ab3e37ba4a4e1b5288612e91f5e4ef2903dd36/src/main/java/com/mcmoddev/golems/EGConfigSpec.java

because this is the config that is generated:

#Golems that can be summoned by villagers
#(Duplicate entries increase chances)
villager_summon_golems = ["golems:golems:bookshelf", "golems:golems:clay", "golems:golems:coal", "golems:golems:crafting", "golems:golems:glass", "golems:golems:glowstone", "golems:golems:hay", "golems:golems:leaves", "golems:golems:log", "golems:golems:melon", "golems:golems:mushroom", "golems:golems:obsidian", "golems:golems:quartz", "golems:golems:red_sandstone", "golems:golems:sandstone", "golems:golems:terracotta", "golems:golems:wool"]

and I can fix it by correcting the names

**Comment by skyjay1** [comment]
Similar to #84 . This issue is fixed for 1.16.5 version, but I haven't gotten around to uploading a fix for 1.17.1 version

**Comment by arketec** [comment]
thats looks to be the same issue. thanks, Ill go ahead and close this as a duplicate
