### ISSUE TITLE
Crash in game by opening golem book

### ISSUE THREAD

**Issue by ClockworkzAI** [MinecraftModDevelopment/Extra-Golems#93]
forge-1.16.5-36.2.9
Also I cant create golems for some reason(I did use the golem head but nothing happens)

[crash-2021-11-16_18.49.11-client.txt](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/files/7548417/crash-2021-11-16_18.49.11-client.txt)

**Comment by LordOscuro** [comment]
I have exactly the same issue. and is a client error. The server doesn´t even notice any error

**Comment by skyjay1** [comment]
Helpful information. But duplicate issue (#89). Sorry I haven't fixed it, I'm very busy with school right now
