### ISSUE TITLE
What mod adds this button and how to disable, please?

### ISSUE THREAD

**Issue by DrizzyBo1** [MinecraftModDevelopment/Extra-Golems#94]
![image](https://user-images.githubusercontent.com/94890780/143778785-42c083f9-8d87-445b-a423-af4291458800.png)
 
someone anyone tell me how to turn this tab off or uninstall this button

**Comment by jriwanek** [comment]
Looks entirely unrelated to Extra Golems, We don't provide support for other people's mods.
