### ISSUE TITLE
Issues with Golems

### ISSUE THREAD

**Issue by PhweeDev** [MinecraftModDevelopment/Extra-Golems#96]
(Note: I am using the latest 1.16.5 release)

This relates to other issues before, but I am unable to get any Golems to spawn naturally in villages. It's always just iron golems.

Before the rewrite. the golems worked fine, although slow, they worked fine.

However, as on 16.5.1/2. the golems won't spawn, and I can't edit the  villager_summon_golems to add alll (except texturable)

To sum up:

ExtraGolems won't spawn when villagers are in distress. 
I can't seem to fit almost all golems in the villager_summon_golems config.
Golems won't spawn as much as I wished (It might be a vanilla thing. I'm not sure)

**Comment by 48004800** [comment]
This problem also exists in 1.19（forge ）.Maybe farbic and so on also have this bug.
