### ISSUE TITLE
Lapis golem crashes the game when fighting 

### ISSUE THREAD

**Issue by Eric-Li-7** [MinecraftModDevelopment/Extra-Golems#98]
I was testing the golems and their attack damage, but when I tested the lapis golem the game crashed with this error:
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.effect.MobEffectInstance.m_19544_()" because "p_34192_" is null
Exit Code: -1

I kept running experiments and found out sometimes when lapis golem fights a mob it does not happen, but sometimes the game just crashes.

**Comment by Eric-Li-7** [comment]
oh and by the way my version is 1.17.1

**Comment by skyjay1** [comment]
This should be fixed in the 1.18 version. Please re-open this issue if the crash continues.
