### ISSUE TITLE
Upsidedown

### ISSUE THREAD

**Issue by Ahmed100Ahmed** [MinecraftModDevelopment/Extra-Golems#99]
The Golems in  Extra Golems Mod are suddenly  Spawning upside down  ... They were fine... Please Help me solve this prblem

**Comment by skyjay1** [comment]
Duplicate of #72 
Hint: check the date

**Comment by Ahmed100Ahmed** [comment]
> Duplicate of #72 Hint: check the date

Witch date? The Date of my computer is correct

**Comment by skyjay1** [comment]
April Fools!

**Comment by skyjay1** [comment]
(You can turn it off by disabling "holiday_tweaks" in the config)

**Comment by Ahmed100Ahmed** [comment]
But I use the version 11.3.1 of Extra golems mod

**Comment by Ahmed100Ahmed** [comment]
> April Fools!

Really???Oh Man

**Comment by Ahmed100Ahmed** [comment]
Thanks Man It works ... now I can go to sleep hahaha
